"""Add color column to vehicles table

Revision ID: 6d1a9cb47ad7
Revises: fc64ecf4ce36
Create Date: 2026-07-30 13:40:00.815022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d1a9cb47ad7'
down_revision: Union[str, Sequence[str], None] = 'fc64ecf4ce36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('color', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'color')
    # ### end Alembic commands ###
